### ISSUE TITLE
How WAN, WLAN, MAN delay works

### ISSUE THREAD

**Issue by ajid951125** [CagataySonmez/EdgeCloudSim#40]
Can you please explain me line 201~208, and I hope to know how the MAN delay works. Are you defining the throughput based on no. of client when defining the experimental delays?? I hope to get your feedback. Thank you.
https://github.com/CagataySonmez/EdgeCloudSim/blob/512b557d3fc4f12f61af945820edb072d4c34586/src/edu/boun/edgecloudsim/applications/sample_app2/SampleNetworkModel.java#L189

**Comment by CagataySonmez** [comment]
Dear @ajid951125,

The man delay is determined via a Markov-modulated Poisson arrival queue (MMPQ) model. Therefore, the average (exponentially distributed) task arrival rate and task size are updated periodically via updateMM1QueeuModel() function.

At the beginning of the simulation, we should predict the average task arrival rate (lambda) and task size since we do not have any historical data. The initialize() function is used for this purpose. Actually, I have just figured out a bug in this function :) I will fix it in the next version, but this is not an important issue, because the initial values are updated after a short time (MM1_QUEUE_MODEL_UPDATE_INTEVAL value is 5 sec for this sample app). You can also use rough initial values for these values based on your simulation scenario.

**Comment by ajid951125** [comment]
Thank you explaining about the MM1Q model for MAN. But as for the WAN, how you determine the experimental delay. I saw you gradually decreasing the value as no. of client increases but I dont understand how can I define those values and is it bandwidth? throughput? I just understood that you use these value based on no. of client to devide with task size for delay calculation. In your paper you did say about empirical model which you observe the fiber line of istanbul. I want to impelement this in my country. It is kind of you to explain it to me.

THANK YOU.

**Comment by CagataySonmez** [comment]
Deat @ajid951125,

We developed a server and client application to observe latency. The architecture of our setup is brifly explained in the attached document. I hope it helps you.

[progress_report-25-26.pdf](https://github.com/CagataySonmez/EdgeCloudSim/files/4450289/progress_report-25-26.pdf)

**Comment by ajid951125** [comment]
Now I understood. Thank you very much.
