### ISSUE TITLE
The usage of "iteration number"

### ISSUE THREAD

**Issue by wangxinqun** [CagataySonmez/EdgeCloudSim#47]
Iteration number has to be set to start simulation process. Could anyone explain the detailed meaning of the iteration number and how it would affect the results? I would appreciate it.

**Comment by kwangalt** [comment]
According to my experience with EdgeCloudSim, here's my opinion:

By default (considering the default sample_apps), the iteration number doesn't change anything apart from showing up in the simulation logs but you will have to name the results folder to match that same number. So it's only convenient that you keep the iteration number as "1" so that you can name your results folder as just "ite1". 

But there's more you can do with this iteration number for instance let's say you're not satisfied with the results of a single iteration then you could go on and run monte-carlo simulations. However much the matlab codes were made ready to handle monte-carlo simulations at once, you may need to run each iteration at a time on the java end. That's to say that you may need to manually create the results folders ite1, ite2,..., ite_n then every time you run the java program, keep changing the iteration number from 1,2,...,n where n is the number of iterations you would like to run. 

Of course, you could go on and modify your MainApp.java file to automatically incorporate the montec-carlo simulations so that you won't have to run the iterations manually because sometimes you might need to run say 10,000 iterations which would be overwhelming doing it manually. 

I hope that helps.

**Comment by wangxinqun** [comment]
Thank you for your time.
I found that if the iteration number is set to be 5, EdgeCloudsim's matlab codes for drawing curves will calculate the average value of ite1,ite2,...,ite5. (You could find it in the 53rd row in plotGenericResult.m. ) I was really confused. I would be grateful if you could explain it.

**Comment by wangxinqun** [comment]
> According to my experience with EdgeCloudSim, here's my opinion:
> 
> By default (considering the default sample_apps), the iteration number doesn't change anything apart from showing up in the simulation logs but you will have to name the results folder to match that same number. So it's only convenient that you keep the iteration number as "1" so that you can name your results folder as just "ite1".
> 
> But there's more you can do with this iteration number for instance let's say you're not satisfied with the results of a single iteration then you could go on and run monte-carlo simulations. However much the matlab codes were made ready to handle monte-carlo simulations at once, you may need to run each iteration at a time on the java end. That's to say that you may need to manually create the results folders ite1, ite2,..., ite_n then every time you run the java program, keep changing the iteration number from 1,2,...,n where n is the number of iterations you would like to run.
> 
> Of course, you could go on and modify your MainApp.java file to automatically incorporate the montec-carlo simulations so that you won't have to run the iterations manually because sometimes you might need to run say 10,000 iterations which would be overwhelming doing it manually.
> 
> I hope that helps.

**Comment by kwangalt** [comment]
I believe that's what monte-carlo simulation is all about (the average).

**Comment by CagataySonmez** [comment]
Hi Wangxinqun,

You have to repeat your experiments many times to avoid the effect of randomization. Iteration number n refers to the nth repetition in your simulation. The result of each iteration is saved under ite[n] folder, like ite1, ite2, etc. The matlab functions plots the graphs by using the average of all results.

If you run simulations via the run_scenarios.sh script, you must provide the number of repetitions as a command line argument. If you manually run the simulations in your IDE (eg eclipse), you need to modify the source code to change the iteration number. 

I usually follow the steps below during the development phase
1- I work on eclipse and run a couple of repetitions (e.g. 3) manually until my app development is finalized
2- I use run_scenarios.sh on linux/macos terminal to run dozens of repetitions (e.g. 100) automatically

I hope this helps,
Cagatay
