### ISSUE TITLE
The meaning of "mean waiting time in seconds"

### ISSUE THREAD

**Issue by wangxinqun** [CagataySonmez/EdgeCloudSim#50]
In the default_config.properties of sample_app5, some parameters are set as:
#mean waiting time in seconds
attractiveness_L1_mean_waiting_time=480
attractiveness_L2_mean_waiting_time=240
attractiveness_L3_mean_waiting_time=120. 

I was confused about their function in simulation.
Could anyone offer guidelines?
Your help will be grateful.

**Comment by CagataySonmez** [comment]
Actually, these values are only used in NomadicMobility.java.
If you search getMobilityLookUpTable() function, you can see that.

In sample_app5, another vehicular mobility model (VehicularMobilityModel.java) is used.
As a result, these values are not functional in this app.

I will remove these values from the config files since it causes a confusion.
Thanks for highlighting!
