### ISSUE TITLE
How you are calculating cost as its always zero.

### ISSUE THREAD

**Issue by shashankshampi** [CagataySonmez/EdgeCloudSim#8]
The cost for the computation is always zero. I tried will different parameters but still getting 0 as a cost result. In your published paper nothing is mentioned about cost and how you are calculating.
If possible can you please give some details about it.

![screenshot from 2018-03-21 11-51-29](https://user-images.githubusercontent.com/20582834/37697767-ae4d541c-2d04-11e8-9aa6-3c5c2a843c9b.png)

**Comment by CagataySonmez** [comment]
Dear Shashank,

Actually, datacenter element defined in edge_devices.xml includes the cost parameters of datacenter:

```
<datacenter arch="x86" os="Linux" vmm="Xen">
	<costPerBw>0.1</costPerBw>
	<costPerSec>3.0</costPerSec>
	<costPerMem>0.05</costPerMem>
	<costPerStorage>0.1</costPerStorage>
    ...
...
```

These parameters are used as the arguments of CloudSim's DatacenterCharacteristics class at line 159 in EdgeServerManager.java:

```
Line 159:	DatacenterCharacteristics characteristics = new DatacenterCharacteristics(arch, os, vmm, hostList, time_zone, costPerSec, costPerMem, costPerStorage, costPerBw);
```

In addition, we have a setter/getter cost function in src/edu/boun/edgecloudsim/utils/SimLogger.java class  to record the cost value.

```
public void setCost(double _bwCost, double _cpuCost)
public double getCost()
```

However, the cost statistics are not collected in the current version (since we didn't need it in the previous works).
As you said, it is always 0 for now.
If you want to collect a custom cost value, you can modify MobileDeviceManager.java class.
At line 192, the task is marked as "completed", you can add a custom cost value after this line:

```
Line 192:	SimLogger.getInstance().downloaded(task.getCloudletId(), CloudSim.clock());
line 193:	SimLogger.getInstance().setCost(customCost1, customCost2);
```

If you want to record more detailed (multiple) cost values, you need to modify SimLogger.java to collect and record related values.


I hope this information will be useful,
Cagatay
